name: Django Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: setup python 3.9
      uses: actions/setup-python@v1
      with:
        python_version: 3.9
    - name: install dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run migrations
        run: hotelproject/Hotel-system/hotelsystem/manage.py migrate

      # run: python hotelsystem/manage.py migrate 
    - name: Run tests
      run: python3 hotelsystem/manage.py test
